import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Note Relay Headless Plugin v2.0
*/
`;

const prod = process.argv[2] === "production";

// Build to local directory for development
const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.js"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  platform: "node",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  console.log("✅ Production build complete");
} else {
  await context.watch();
  console.log("👀 Watching for changes...");
}
